### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.metadata'`

### ISSUE THREAD

**Issue by simonox** [Guardsquare/appsweep-action#16]
## ModuleNotFoundError

We are using the main version:
```
- uses: guardsquare/appsweep-action@main
```

When running it, we get an error (from the Docker container log):

```
Traceback (most recent call last):
  File "/app/main.py", line 4, in <module>
    import requests
  File "/app/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/app/urllib3/__init__.py", line 18, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/app/urllib3/connectionpool.py", line [15](https://.../apps/android/actions/runs/81647/job/314752#step:13:16), in <module>
    from ._request_methods import RequestMethods
  File "/app/urllib3/_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "/app/urllib3/response.py", line 48, in <module>
    from .connection import BaseSSLError, HTTPConnection, HTTPException
  File "/app/urllib3/connection.py", line 24, in <module>
    from .http2 import probe as http2_probe
  File "/app/urllib3/http2/__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'
```

These errors started on 2024-10-01. It worked well, before (like 3 weeks ago).

### GitHub

We are using a self-hosted GitHub.

### Action details
```
name: Release the Android app to stores
run-name: ${{ github.actor }} is running  the 🚀 release job for the 🦾 Android app
on:
    release:
      types: [ published ]
    workflow_dispatch:
jobs:
  release-actions:
    runs-on: [ self-hosted ]
    steps:
      - name: Upload to 👮 GuardSquare AppSweep  
      - uses: guardsquare/appsweep-action@main
        with:
          appsweep_api_key: ${{ secrets.APPSWEEP_API_KEY }}
          input_file: app/build/outputs/apk/......-release.apk
          commit_hash: ${{ github.sha }}
          tags: ......
```

### Output
```
Run guardsquare/appsweep-action@main
/usr/bin/docker run --name d058f882591f4bbe4508bcbb3ffba44314aa_e1d909 --label 72d058 --workdir /github/workspace --rm -e "commit_message" -e "tag_name" -e "INPUT_APPSWEEP_API_KEY" -e "INPUT_INPUT_FILE" -e "INPUT_COMMIT_HASH" -e "INPUT_TAGS" -e "INPUT_MAPPING_FILE" -e "INPUT_LIBRARY_FILE" -e "INPUT_URL" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/github-runner-apps-1/_temp/_github_home":"/github/home" -v "/github-runner-apps-1/_temp/_github_workflow":"/github/workflow" -v "/github-runner-apps-1/_temp/_runner_file_commands":"/github/file_commands" -v "/github-runner-apps-1/android/android":"/github/workspace" 72d058:f882591f4bbe4508bcbb3ffba44314aa
Traceback (most recent call last):
  File "/app/main.py", line 4, in <module>
    import requests
  File "/app/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/app/urllib3/__init__.py", line 18, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/app/urllib3/connectionpool.py", line [15](https://srv-git-01-hh1.alinghi.tipp24.net/apps/android/actions/runs/81647/job/315734#step:13:16), in <module>
    from ._request_methods import RequestMethods
  File "/app/urllib3/_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "/app/urllib3/response.py", line 48, in <module>
    from .connection import BaseSSLError, HTTPConnection, HTTPException
  File "/app/urllib3/connection.py", line 24, in <module>
    from .http2 import probe as http2_probe
  File "/app/urllib3/http2/__init__.py", line 3, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'
```

**Comment by titze** [comment]
Hey @simonox,

a fix for this is incoming shortly: https://github.com/Guardsquare/appsweep-action/pull/17

All the best,
Dennis

**Comment by foadjn** [comment]
Hi @simonox,

We've just released a new version of AppSweep Github action. Could you please give it a try and let us know if everything works as expected?

Best,
Foad

**Comment by foadjn** [comment]
Hey @simonox,

We're glad to hear you're using Guardsquare CLI. I'm writing to close this issue as we believe the reported problem has been addressed. We've thoroughly tested the solution and haven't encountered any further issues.

If you encounter any related problems or have any further questions, please don't hesitate to open a new issue. We're always here to assist you.

Thank you for your valuable feedback and for using AppSweep.

Best,
Foad
